### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/nhsr-helpful-packages#2]
Probably would be useful to add how to contribute to the repo here, either via airtable or PR

**Comment by jasonpott** [comment]
Sure sounds good. Shall we do this via a subpage, or just link to the form and slack info on the main page?

**Comment by ChrisBeeley** [comment]
Just in the README is fine I think, thanks

**Comment by jasonpott** [comment]
commit a6aeeb9 has added this information and a link to the form. I have also added some help text to the form to make the submission easier.

**Comment by jasonpott** [comment]
commit a6aeeb9 has added this information and a link to the form. I have also added some help text to the form to make the submission easier.
